apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: foreldrepenger-alerts
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  groups:
    - name: foreldrepenger-alerts
      rules:
        - record: is_european_summer_time
          expr: |
            (vector(1) and (month() > 3 and month() < 10))
            or
            (vector(1) and (month() == 3 and (day_of_month() - day_of_week()) >= 25) and absent((day_of_month() >= 25) and (day_of_week() == 0)))
            or
            (vector(1) and (month() == 10 and (day_of_month() - day_of_week()) < 25) and absent((day_of_month() >= 25) and (day_of_week() == 0)))
            or
            (vector(1) and ((month() == 10 and hour() < 1) or (month() == 3 and hour() > 0)) and ((day_of_month() >= 25) and (day_of_week() == 0)))
            or
            vector(0)
        - record: european_time
          expr: time() + 3600 * (is_european_summer_time + 1)
        - record: european_hour
          expr: hour(european_time)
        - alert: Feilede prosesstask i applikasjon
          expr: |
            round(avg (prosesstask_antall{namespace="teamforeldrepenger", status="feilet"}) by (app)) > 0
            and on() european_hour == 8
          for: 5m
          annotations:
            summary: 'Applikasjonen *{{ $labels.app }}* har {{ $value }} feilede prosesstasks!'
          labels:
            namespace: teamforeldrepenger
            severity: warning
            special_type_to_use_in_alertmanager_config: foreldrepenger-none-resolve-alert
            alert_type: custom

        - alert: Nye feilede prosesstask registert
          expr: |
            round((sum (prosesstask_antall{namespace="teamforeldrepenger",status="feilet"}) by (app) -
            sum (prosesstask_antall{namespace="teamforeldrepenger",status="feilet"} offset 10m) by (app)) /
            count (prosesstask_antall{namespace="teamforeldrepenger", status="feilet"})  by (app)) > 0.5
            and
            avg (prosesstask_antall{namespace="teamforeldrepenger",status="feilet"}) by (app) > 0
          for: 5m
          annotations:
            summary: 'Applikasjonen *{{ $labels.app }}* har {{ $value }} nye feilede prosesstasks de siste 5 minuttene!'
          labels:
            namespace: teamforeldrepenger
            severity: warning
            special_type_to_use_in_alertmanager_config: foreldrepenger-none-resolve-alert
            alert_type: custom

        - alert: Mange errors/warnings observert i loggen de siste 5 minuttene
          expr: sum (floor(increase(logback_events_total{namespace="teamforeldrepenger", level=~"error|warn"}[5m]))) by (app) > 4
          annotations:
            summary: '{{ $value }} warnings/errors har blitt observert i loggen til *{{ $labels.app }}*'
          labels:
            namespace: teamforeldrepenger
            severity: warning
            special_type_to_use_in_alertmanager_config: foreldrepenger-none-resolve-alert
            alert_type: custom

        - alert: Applikasjonen er nede
          expr: kube_deployment_status_replicas_available{namespace="teamforeldrepenger"} == 0
          for: 30s
          annotations:
            summary: '*{{ $labels.deployment }}* er nede og ikke tilgjengelig!'
          labels:
            namespace: teamforeldrepenger
            severity: critical

        # Alarmer behandlingårsak
        - alert: Behandlingårsak opprettet fra nye hendelser i folkeregisteret (PDL)
          expr: |
            delta(max(fp_behandlinger_antall{behandling_aarsak_type="FOLKEREGISTER"})[100m:]) == 0 
            and on() (day_of_week() > 0 and day_of_week() < 6)
            and on() (european_hour >= 9 and european_hour < 23)
          for: 20m
          annotations:
            summary: 'Ingen nye behandlinger med behandlingårsak fra folkeregisteret (PDL) de siste 2 timene'
          labels:
            namespace: teamforeldrepenger
            severity: warning

        # Alarmer for mottatte dokumenter
        - alert: Førstegangssøknad foreldrepenger
          expr: |
            delta(max(fp_dokument_antall{dokument_type="FORELDREPENGER"})[40m:]) == 0 
            and on() (day_of_week() > 0 and day_of_week() < 6)
            and on() (european_hour >= 9 and european_hour < 21)
          for: 20m
          annotations:
            summary: 'Ingen nye førstegangssøknader på foreldrepenger den siste timen!'
          labels:
            namespace: teamforeldrepenger
            severity: warning

        - alert: Revurdering foreldrepenger
          expr: |
            delta(max(fp_dokument_antall{dokument_type="ENDRINGSSØKNAD"})[40m:]) == 0 
            and on() (day_of_week() > 0 and day_of_week() < 6)
            and on() (european_hour >= 9 and european_hour < 21)
          for: 20m
          annotations:
            summary: 'Ingen nye revurderinger på foreldrepenger den siste timen!'
          labels:
            namespace: teamforeldrepenger
            severity: warning

        - alert: Førstegangssøknad svangerskapspenger
          expr: |
            delta(max(fp_dokument_antall{dokument_type="SVANGERSKAPSPENGER"})[160m:]) == 0 
            and on() (day_of_week() > 0 and day_of_week() < 6)
            and on() (european_hour >= 11 and european_hour < 21)
          for: 20m
          annotations:
            summary: 'Ingen nye førstegangssøknader på svangerskapspenger de siste 3 timene!'
          labels:
            namespace: teamforeldrepenger
            severity: warning

        - alert: Førstegangssøknad engangsstønad
          expr: |
            delta(max(fp_dokument_antall{dokument_type="ENGANGSSTØNAD"})[160m:]) == 0 
            and on() (day_of_week() > 0 and day_of_week() < 6)
            and on() (european_hour >= 11 and european_hour < 21)
          for: 20m
          annotations:
            summary: 'Ingen nye førstegangssøknader på engangsstønad de siste 3 timene!'
          labels:
            namespace: teamforeldrepenger
            severity: warning

        - alert: Ettersendelse av dokumentasjon
          expr: |
            delta(max(fp_dokument_antall{dokument_type=~"SYKDOM|AKTIVITETSKRAV|FAMHENDELSE|ANNET"})[100m:]) == 0 
            and on() (day_of_week() > 0 and day_of_week() < 6)
            and on() (european_hour >= 10 and european_hour < 21)
          for: 20m
          annotations:
            summary: 'Ingen nye ettersendelser av dokumentasjon de siste 2 timene!'
          labels:
            namespace: teamforeldrepenger
            severity: warning

        - alert: Inntektsmeldinger mottatt
          expr: |
            delta(max(fp_dokument_antall{dokument_type="INNTEKTSMELDING"})[40m:]) == 0 
            and on() (day_of_week() > 0 and day_of_week() < 6)
            and on() (european_hour >= 9 and european_hour < 17)
          for: 20m
          annotations:
            summary: 'Ingen inntektsmeldinger mottatt den siste timen!'
          labels:
            namespace: teamforeldrepenger
            severity: warning