apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: familie-vedtakfattet-v1
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
     {{key}}: {{value}}
  {{/each}}
  acl:
    - team: teamforeldrepenger
      application: fpsak
      access: readwrite
    - team: teamforeldrepenger
      application: fpabakus
      access: read
    - team: teamforeldrepenger
      application: fpabonnent
      access: read
    - team: teamforeldrepenger
      application: fptilbake
      access: read
    - team: k9saksbehandling
      application: k9-sak
      access: readwrite
    - team: k9saksbehandling
      application: k9-tilbake
      access: read
    - team: k9saksbehandling
      application: k9-statistikk
      access: read
