apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: familie-vedtakFattet-v1
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
     {{key}}: {{value}}
  {{/each}}
  acl:
    - team: teamforeldrepenger
      application: fpsak
      access: readwrite
    - team: teamforeldrepenger
      application: fpabakus
      access: read
    - team: teamforeldrepenger
      application: fpabonnent
      access: read
    - team: teamforeldrepenger
      application: fptilbake
      access: read
    - team: teamforeldrepenger
      application: fp-kafka-manager
      access: read