apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: selvbetjening-innsendinghendelse-v1
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
     {{key}}: {{value}}
  {{/each}}
  acl:
    - team: teamforeldrepenger
      application: fpsoknad-mottak
      access: write
    - team: teamforeldrepenger
      application: fpinfo-historikk
      access: read
  {{#each acl}}
    - team: {{team}}
      application: {{app}}
      access: {{access}}
  {{/each}}
