pool: nav-prod
config:
  cleanupPolicy: delete # delete or compact
  minimumInSyncReplicas: 2
  partitions: 2
  replication: 3
  retentionBytes: -1
  retentionHours: 504 # 3 uker
acl:
  - team: ptsak
    app: pt-sak-fptilbake
    access: read