apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: tilbakekreving-brukerdialog-v1
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
     {{key}}: {{value}}
  {{/each}}
  acl:
    - team: teamforeldrepenger
      application: fptilbake
      access: write
    - team: teamforeldrepenger
      application: fpinfo-historikk
      access: read
