apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: familie-redirect-nginx
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
    nginx.ingress.kubernetes.io/permanent-redirect: https://www.nav.no/barn
    nginx.ingress.kubernetes.io/permanent-redirect-code: "301"
  ingressClassName: nais-ingress-external
  rules:
    - host: familie.nav.no
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dummy-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: familie-redirect-haproxy
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
  annotations:
    haproxy.org/request-redirect: "https://www.nav.no/barn"
spec:
  ingressClassName: external-haproxy
  rules:
    - host: familie.nav.no
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dummy-service
                port:
                  number: 80
