apiVersion: v1
kind: Service
metadata:
  name: familie-redirect-til-barn
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: familie-haproxy-redirect
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
  annotations:
    haproxy.org/backend-config-snippet: |
      http-request redirect location https://www.nav.no/barn code 301
spec:
  ingressClassName: external-haproxy
  rules:
    - host: familie.nav.no
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: familie-redirect-til-barn
                port:
                  number: 80
