apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: foreldrepenger-alerts
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  groups:
    - name: foreldrepenger-alerts
      rules:
        - alert: Applikasjonen er nede
          expr: kube_deployment_status_replicas_available{namespace="teamforeldrepenger"} == 0
          for: 30s
          annotations:
            summary: '*{{ $labels.deployment }}* er nede og ikke tilgjengelig!'
          labels:
            namespace: teamforeldrepenger
            severity: critical

        - alert: Feilede prosesstask i applikasjon
          expr: |
            round(sum (prosesstask_antall{namespace="teamforeldrepenger", status="feilet"}) by (app) /
            count (prosesstask_antall{namespace="teamforeldrepenger", status="feilet"})  by (app)) > 0
          for: 5m
          annotations:
            summary: 'Applikasjonen *{{ $labels.app }}* har {{ $value }} feilede prosesstasks!'
          labels:
            namespace: teamforeldrepenger
            severity: warning
            special_type_to_use_in_alertmanager_config: foreldrepenger-prosesstask-alert
            alert_type: custom

        - alert: Nye feilede prosesstask registert
          expr: |
            round((sum (prosesstask_antall{namespace="teamforeldrepenger",status="feilet"}) by (app) -
            sum (prosesstask_antall{namespace="teamforeldrepenger",status="feilet"} offset 10m) by (app)) /
            count (prosesstask_antall{namespace="teamforeldrepenger", status="feilet"})  by (app)) > 0.5
            and
            sum (prosesstask_antall{namespace="teamforeldrepenger",status="feilet"}) by (app) > 0
          for: 5m
          annotations:
            summary: 'Applikasjonen *{{ $labels.app }}* har {{ $value }} nye feilede prosesstasks de siste 5 minuttene!'
          labels:
            namespace: teamforeldrepenger
            severity: warning

        - alert: Flere errors/warnings observert i loggen de siste 5 minuttene
          expr: sum (floor(increase(logback_events_total{namespace="teamforeldrepenger", level=~"error|warn"}[5m]))) by (app) > 2
          annotations:
            summary: '{{ $value }} warnings/errors har blitt observert i loggen til *{{ $labels.app }}*'
          labels:
            namespace: teamforeldrepenger
            severity: warning