name: Deploy alerts topics

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-alert-gcp.yml
      - alert/gcp/**
      - alert/foreldrepenger-alerts.yaml
jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2

      - name: Deploy alertconfig to prod-gcp
        uses: nais/deploy/actions/deploy@8ed36847e27a937bb9cd9b3751b1a5fff8ef31dc # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: alert/foreldrepenger-alertconfig.yaml
          PRINT_PAYLOAD: true

      - name: Deploy to prod-gcp
        uses: nais/deploy/actions/deploy@8ed36847e27a937bb9cd9b3751b1a5fff8ef31dc # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: alert/gcp/foreldrepenger-alerts.yaml
          PRINT_PAYLOAD: true
