name: Deploy redirects

on:
  push:
    branches:
     - main
    paths:
      - .github/workflows/deploy-redirect.yml
      - redirect/**
jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy redirect foreldrepenger-inngang prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: redirect/redirect.yml
          VARS: redirect/foreldrepenger-inngang.json
          PRINT_PAYLOAD: true