name: Deploy alerts topics

on:
  push:
    branches:
     - main
    paths:
      - .github/workflows/deploy-alert-fss.yml
      - alert/fss/**
jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy alertconfig to prod-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: alert/foreldrepenger-alertconfig.yaml
          PRINT_PAYLOAD: true

      - name: Deploy to prod-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: alert/fss/foreldrepenger-alerts.yaml
          PRINT_PAYLOAD: true