name: Deploy redirects

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-redirect.yml
      - redirect/**
jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v6.0.3

      - name: Deploy redirect familie to prod
        uses: nais/deploy/actions/deploy@ab841e4d99cbb00edd996d3ae39bd4cea6b8e2c2 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: redirect/redirect-familie.yml
          PRINT_PAYLOAD: true
