name: Deploy redis

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-redis.yml
      - redis/**
jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1

      - name: Deploy fpcache to dev-fss
        uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: redis/fpcache-redis.yaml
          PRINT_PAYLOAD: true

      - name: Deploy to fpcache to prod-fss
        if: success()
        uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: redis/fpcache-redis.yaml
          PRINT_PAYLOAD: true
